### ISSUE TITLE
As an Alpinebits destinationdata developer i want to have a repository and a deployment for the openapi swagger page

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/odh-alpinebits-destination-data-proxy#3]
- [ ] Provide Repository
- [x] Discuss Deployment strategy
- [x] Deploy in rooturl/swagger

**Comment by Piiit** [comment]
A solution could be to use our general swagger server like ninja does:
https://swagger.opendatahub.bz.it/?url=https://mobility.api.opendatahub.bz.it/v2/apispec

We also have a redirection: https://mobility.api.opendatahub.bz.it

**Comment by RudiThoeni** [comment]
unibz repo
https://github.com/claudenirmf/odh-alpinebits-dd-openapi

swagger is here
https://claudenirmf.github.io/odh-alpinebits-dd-openapi/swagger/

**Comment by RudiThoeni** [comment]
Cool the swagger server ;)

Working with the tourism swagger definition
https://swagger.opendatahub.bz.it/?url=https://tourism.api.opendatahub.bz.it/swagger/v1/swagger.json

the swagger spec from unibz is here 
https://claudenirmf.github.io/odh-alpinebits-dd-openapi/swagger/specification.js

it gives a parser error because of this "specification =" on beginning.... i will ask unibz if they can provide a clean swagger definition

**Comment by RudiThoeni** [comment]
Simplest solution is to use our repo for the Alpinebits Destinationdata proxy, include the openapi generation in the deployment of this repo and use the swagger.opendatahub.bz.it

Can already be tested 
https://swagger.opendatahub.bz.it/?url=https://destinationdata.alpinebits.opendatahub.bz.it/specification.json
(inserted and deployed manually)

**Comment by RudiThoeni** [comment]
Waiting for claudenirs PR on alpinebits destinationdata proxy repo which includes all stuff to generate the specification openapi file

**Comment by RudiThoeni** [comment]
done swagger link also on destinationdata starting point
https://destinationdata.alpinebits.opendatahub.bz.it/

**Comment by Piiit** [comment]
@RudiThoeni Nice, but in the dropdown of the swagger spec you have still the example.com entry :-)

**Comment by RudiThoeni** [comment]
yes, i have to tell claudenir in the meeting today it is only this here to correct
https://github.com/noi-techpark/odh-alpinebits-destination-data-proxy/blob/development/openapi/src/index.yml
